OPENAI_API_KEY='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'
#neo4j_pass ='graphrag'
NEO4J_URI='neo4j+s://e52dbfe1.databases.neo4j.io'
NEO4J_USERNAME='neo4j'
NEO4J_PASSWORD='PG23O6RpzVDBU-s35GJ7aIlW57E8o2ej9IXxWiIyuFY'
